// Receitas-base (1 porção). O planejador escala as gramas para bater a meta de cada refeição.
// slot: cafe · lanche (também usado na ceia) · refeicao (almoço/jantar)
export const RECIPES = [
  // ---------------- Café da manhã ----------------
  { id: 'cuscuz_ovos', n: 'Cuscuz nordestino com ovos mexidos', slot: 'cafe', min: 10,
    ing: [['cuscuz', 150], ['ovo', 100], ['tomate', 40], ['azeite', 3]],
    steps: ['Hidrate o flocão com água e uma pitada de sal por 10 min e cozinhe no vapor (cuscuzeira) por 8–10 min.', 'Mexa os ovos em frigideira antiaderente untada com o azeite.', 'Sirva com tomate picado por cima.'] },
  { id: 'tapioca_frango', n: 'Tapioca de frango com queijo branco', slot: 'cafe', min: 10,
    ing: [['tapioca', 60], ['frango_desf', 60], ['queijo_minas', 30], ['tomate', 30]],
    steps: ['Espalhe a goma na frigideira quente sem óleo até firmar (1–2 min).', 'Recheie com frango desfiado, queijo e tomate.', 'Dobre e aqueça mais 1 min de cada lado.'] },
  { id: 'crepioca', n: 'Crepioca de queijo', slot: 'cafe', min: 8,
    ing: [['ovo', 100], ['tapioca', 30], ['queijo_minas', 30], ['mamao', 100]],
    steps: ['Bata os ovos com a goma de tapioca e uma pitada de sal.', 'Despeje na frigideira antiaderente e doure dos dois lados.', 'Recheie com o queijo e sirva com o mamão.'] },
  { id: 'ovos_pao', n: 'Ovos mexidos com pão integral e mamão', slot: 'cafe', min: 8,
    ing: [['ovo', 100], ['pao_integral', 50], ['mamao', 150], ['azeite', 3]],
    steps: ['Mexa os ovos em fogo baixo com o azeite até ficarem cremosos.', 'Toste o pão.', 'Sirva com o mamão.'] },
  { id: 'panqueca_banana', n: 'Panqueca de banana e aveia', slot: 'cafe', min: 10,
    ing: [['banana', 70], ['ovo', 100], ['aveia', 30], ['mel', 5]],
    steps: ['Amasse a banana e misture com os ovos e a aveia (canela a gosto).', 'Doure porções na frigideira antiaderente, 2 min de cada lado.', 'Finalize com o mel.'] },
  { id: 'iogurte_aveia', n: 'Iogurte com aveia, morango e chia', slot: 'cafe', min: 3,
    ing: [['iogurte', 170], ['aveia', 30], ['morango', 100], ['chia', 10]],
    steps: ['Monte em camadas: iogurte, aveia e morangos picados.', 'Finalize com a chia.'] },
  { id: 'vitamina_whey', n: 'Vitamina proteica de banana', slot: 'cafe', min: 3,
    ing: [['leite', 250], ['banana', 70], ['aveia', 20], ['whey', 25]],
    steps: ['Bata tudo no liquidificador com gelo.', 'Beba em seguida.'] },
  { id: 'tofu_mexido', n: 'Tofu mexido com pão integral', slot: 'cafe', min: 10,
    ing: [['tofu', 120], ['pao_integral', 50], ['tomate', 50], ['azeite', 5]],
    steps: ['Esfarele o tofu e refogue no azeite com cúrcuma, sal e pimenta por 5 min.', 'Junte o tomate picado.', 'Sirva com o pão tostado.'] },
  { id: 'pao_amendoim', n: 'Pão integral com pasta de amendoim e banana', slot: 'cafe', min: 3,
    ing: [['pao_integral', 50], ['pasta_amend', 20], ['banana', 70]],
    steps: ['Passe a pasta de amendoim no pão.', 'Cubra com rodelas de banana (canela a gosto).'] },

  // ---------------- Lanches / ceia ----------------
  { id: 'iogurte_granola', n: 'Iogurte com granola e mamão', slot: 'lanche', min: 2,
    ing: [['iogurte', 170], ['granola', 25], ['mamao', 100]],
    steps: ['Misture o iogurte com o mamão picado e finalize com a granola.'] },
  { id: 'maca_amendoim', n: 'Maçã com pasta de amendoim', slot: 'lanche', min: 2,
    ing: [['maca', 130], ['pasta_amend', 15]],
    steps: ['Fatie a maçã e sirva com a pasta de amendoim.'] },
  { id: 'sanduiche_frango', n: 'Sanduíche natural de frango', slot: 'lanche', min: 5,
    ing: [['pao_integral', 50], ['frango_desf', 50], ['ricota', 20], ['cenoura', 20], ['alface', 10]],
    steps: ['Misture o frango com a ricota e a cenoura ralada (sal e ervas a gosto).', 'Monte no pão com a alface.'] },
  { id: 'ovos_banana', n: 'Ovos cozidos com banana', slot: 'lanche', min: 12,
    ing: [['ovo', 100], ['banana', 70]],
    steps: ['Cozinhe os ovos por 9–10 min em água fervente.', 'Sirva com a banana.'] },
  { id: 'shake_whey', n: 'Shake de whey com banana', slot: 'lanche', min: 2,
    ing: [['whey', 30], ['banana', 70]],
    steps: ['Bata o whey com a banana, 200 ml de água e gelo.'] },
  { id: 'castanha_fruta', n: 'Castanhas com maçã', slot: 'lanche', min: 1,
    ing: [['castanha', 12], ['maca', 130]],
    steps: ['Sirva as castanhas com a maçã.'] },
  { id: 'cottage_morango', n: 'Cottage com morango e mel', slot: 'lanche', min: 2,
    ing: [['cottage', 100], ['morango', 100], ['mel', 7]],
    steps: ['Misture o cottage com os morangos picados e regue com o mel.'] },
  { id: 'homus_cenoura', n: 'Homus com palitos de cenoura', slot: 'lanche', min: 10,
    ing: [['grao_bico', 80], ['azeite', 5], ['cenoura', 80]],
    steps: ['Bata o grão-de-bico cozido com o azeite, limão, alho, sal e um pouco de água até virar pasta.', 'Sirva com a cenoura em palitos.'] },
  { id: 'iogurte_chia', n: 'Iogurte natural com chia', slot: 'lanche', min: 2,
    ing: [['iogurte', 170], ['chia', 10]],
    steps: ['Misture e deixe descansar 5 min para a chia hidratar.'] },

  // ---------------- Almoço / jantar ----------------
  { id: 'prato_classico', n: 'Arroz, feijão, frango grelhado e salada', slot: 'refeicao', min: 25,
    ing: [['arroz', 120], ['feijao', 100], ['frango', 120], ['alface', 30], ['tomate', 50], ['azeite', 5]],
    steps: ['Tempere o filé com sal, alho e limão e grelhe 4–5 min de cada lado.', 'Sirva com arroz e feijão.', 'Monte a salada e regue com o azeite.'] },
  { id: 'patinho_abobora', n: 'Patinho moído com purê de abóbora e brócolis', slot: 'refeicao', min: 25,
    ing: [['patinho', 120], ['abobora', 150], ['brocolis', 80], ['cebola', 20], ['azeite', 5]],
    steps: ['Refogue a cebola no azeite, junte a carne e cozinhe até dourar (sal, alho, cheiro-verde).', 'Cozinhe a abóbora e amasse até virar purê.', 'Cozinhe o brócolis no vapor por 5 min.'] },
  { id: 'tilapia_batata', n: 'Tilápia com batata-doce e legumes', slot: 'refeicao', min: 30,
    ing: [['tilapia', 150], ['batata_doce', 150], ['brocolis', 80], ['cenoura', 50], ['azeite', 5]],
    steps: ['Tempere a tilápia com limão, sal e páprica e grelhe 3–4 min de cada lado.', 'Cozinhe a batata-doce em cubos.', 'Cozinhe os legumes no vapor e regue com o azeite.'] },
  { id: 'escondidinho', n: 'Escondidinho de mandioca com frango', slot: 'refeicao', min: 40,
    ing: [['mandioca', 150], ['frango_desf', 120], ['molho_tomate', 50], ['cebola', 20], ['mucarela', 20]],
    steps: ['Cozinhe a mandioca e amasse até virar purê (sal a gosto).', 'Refogue o frango com cebola e molho de tomate.', 'Monte em camadas (frango embaixo, purê em cima), cubra com a muçarela e gratine por 10 min.'] },
  { id: 'macarrao_atum', n: 'Macarrão integral ao sugo com atum', slot: 'refeicao', min: 20,
    ing: [['macarrao_int', 150], ['atum', 80], ['molho_tomate', 80], ['azeite', 5]],
    steps: ['Cozinhe o macarrão al dente.', 'Aqueça o molho com o atum escorrido e orégano.', 'Misture com a massa e finalize com o azeite.'] },
  { id: 'strogonoff_fit', n: 'Strogonoff fit de frango com arroz', slot: 'refeicao', min: 25,
    ing: [['frango', 130], ['iogurte', 60], ['molho_tomate', 40], ['cebola', 20], ['arroz', 100]],
    steps: ['Doure o frango em cubos com a cebola.', 'Junte o molho de tomate e cozinhe 5 min.', 'Desligue o fogo e misture o iogurte (não ferva para não talhar). Sirva com arroz.'] },
  { id: 'carne_panela', n: 'Carne de panela com batata e cenoura', slot: 'refeicao', min: 50,
    ing: [['acem', 120], ['batata', 120], ['cenoura', 60], ['cebola', 20], ['arroz', 80]],
    steps: ['Sele a carne em cubos, junte cebola, alho e água e cozinhe na pressão por 25 min.', 'Acrescente batata e cenoura e cozinhe mais 8 min.', 'Sirva com arroz.'] },
  { id: 'omelete_legumes', n: 'Omelete de legumes com arroz integral e salada', slot: 'refeicao', min: 15,
    ing: [['ovo', 150], ['abobrinha', 60], ['tomate', 40], ['queijo_minas', 30], ['arroz_int', 80], ['alface', 30]],
    steps: ['Bata os ovos com sal e ervas.', 'Refogue a abobrinha e o tomate, despeje os ovos e o queijo e cozinhe tampado em fogo baixo.', 'Sirva com arroz integral e salada.'] },
  { id: 'lentilha_arroz', n: 'Lentilha com arroz integral e abóbora', slot: 'refeicao', min: 35,
    ing: [['lentilha', 150], ['arroz_int', 120], ['abobora', 100], ['azeite', 5]],
    steps: ['Cozinhe a lentilha com louro e alho por 20 min.', 'Asse ou cozinhe a abóbora em cubos.', 'Sirva com o arroz e regue com o azeite.'] },
  { id: 'tofu_brocolis', n: 'Tofu grelhado com arroz integral e brócolis', slot: 'refeicao', min: 20,
    ing: [['tofu', 150], ['arroz_int', 120], ['brocolis', 100], ['azeite', 5]],
    steps: ['Seque o tofu, corte em fatias e grelhe no azeite com shoyu reduzido em sódio.', 'Cozinhe o brócolis no vapor.', 'Sirva com o arroz integral.'] },
  { id: 'sardinha_cuscuz', n: 'Sardinha com cuscuz e salada', slot: 'refeicao', min: 15,
    ing: [['sardinha', 90], ['cuscuz', 150], ['tomate', 60], ['pepino', 60], ['cebola', 20]],
    steps: ['Prepare o cuscuz no vapor.', 'Escorra a sardinha e desfie por cima.', 'Sirva com salada de tomate, pepino e cebola (limão a gosto).'] },
  { id: 'grao_bico_curry', n: 'Grão-de-bico ao curry com arroz integral', slot: 'refeicao', min: 25,
    ing: [['grao_bico', 150], ['arroz_int', 100], ['molho_tomate', 60], ['cebola', 20], ['brocolis', 60], ['azeite', 5]],
    steps: ['Refogue a cebola no azeite com curry, cúrcuma e alho.', 'Junte o grão-de-bico cozido e o molho de tomate e cozinhe 10 min.', 'Sirva com arroz integral e brócolis no vapor.'] },
  { id: 'feijao_batata_doce', n: 'Arroz, feijão, batata-doce e salada', slot: 'refeicao', min: 25,
    ing: [['arroz', 100], ['feijao', 150], ['batata_doce', 120], ['alface', 30], ['tomate', 60], ['azeite', 5]],
    steps: ['Cozinhe a batata-doce em cubos (ou asse com ervas).', 'Sirva com arroz e uma concha generosa de feijão.', 'Monte a salada e regue com o azeite.'] },
  { id: 'bolonhesa_lentilha', n: 'Macarrão integral à bolonhesa de lentilha', slot: 'refeicao', min: 30,
    ing: [['macarrao_int', 140], ['lentilha', 120], ['molho_tomate', 80], ['cebola', 20], ['azeite', 5]],
    steps: ['Cozinhe a lentilha até ficar macia, sem desmanchar.', 'Refogue a cebola no azeite, junte a lentilha e o molho e apure 10 min (orégano e manjericão).', 'Misture com o macarrão cozido al dente.'] },
  { id: 'grao_bico_frango', n: 'Frango com grão-de-bico e legumes', slot: 'refeicao', min: 25,
    ing: [['frango', 120], ['grao_bico', 100], ['abobrinha', 80], ['cenoura', 50], ['azeite', 5]],
    steps: ['Grelhe o frango em cubos com páprica.', 'Refogue os legumes e junte o grão-de-bico cozido.', 'Misture tudo e finalize com azeite e salsinha.'] },
];
